import 'dotenv/config'

console.log('🔧 Setting up local webhook testing...')
console.log('')
console.log('📋 Follow these steps:')
console.log('')
console.log('1. Install Stripe CLI:')
console.log('   brew install stripe/stripe-cli/stripe')
console.log('')
console.log('2. Login to Stripe:')
console.log('   stripe login')
console.log('')
console.log('3. Start webhook forwarding (in a new terminal):')
console.log('   stripe listen --forward-to localhost:3000/api/webhooks/stripe')
console.log('')
console.log('4. Copy the webhook secret from the CLI output and add to your .env file:')
console.log('   STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxxxxxxxxxx')
console.log('')
console.log('5. Start your development server:')
console.log('   pnpm dev')
console.log('')
console.log('6. Test the checkout flow!')
console.log('')
console.log('💡 The Stripe CLI will show you all webhook events in real-time.')
console.log('💡 Your webhook endpoint will receive events and update user records.')
